# Generated by cucumber-sinatra. (2014-01-28 16:35:00 +0300)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')
require File.join(File.dirname(__FILE__), '..', 'config.rb')


require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = App

class AppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  AppWorld.new
end


